name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          lfs: true
          fetch-depth: 0
      - uses: chetan/git-restore-mtime-action@v2
        with:
          working-directory: 'apks'
      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          cache: true
          run_install: true
      - uses: actions/setup-node@v6
      - run: node generator.mjs
      - run: curl -L https://github.com/tdewolff/minify/releases/download/v2.24.13/minify_linux_amd64.tar.gz | tar -xz && ./minify -r -i ./deploy/
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'deploy'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
